version: '3.8'
services:
  client:
    image: 'node:16-bullseye'
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
    working_dir: /client
    command: bash -c 'npm install && npm start'

  server:
    image: 'node:16-bullseye'
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
    working_dir: /server
    command: bash -c 'npm install && npm start'
    depends_on:
      - 'mongo'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
      - ./server/app/models/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: pass1234
      MONGO_INITDB_DATABASE: 'mydb'

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1234
    restart: unless-stopped
    depends_on:
      - 'mongo'

volumes:
  mongodb:
